name: CI Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      LAGRAPH_DIR: ~/lagraph
      GRAPHBLAS_USE_JIT: 0
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-format clang-tidy \
            cmake build-essential \
            libgomp1 libomp-dev

      - name: Cache GraphBLAS
        id: cache-graphblas
        uses: actions/cache@v5
        with:
          path: ~/graphblas
          key: graphblas-${{ runner.os }}-v1

      - name: Build & Install GraphBLAS
        if: steps.cache-graphblas.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/DrTimothyAldenDavis/GraphBLAS.git ~/graphblas
          cd ~/graphblas
          make compact

      - name: Install GraphBLAS
        run: |
          cd ~/graphblas
          sudo make install

      - name: Cache LAGraph
        id: cache-lagraph
        uses: actions/cache@v5
        with:
          path: ~/lagraph
          key: lagraph-${{ runner.os }}-v1

      - name: Clone LAGraph
        if: steps.cache-lagraph.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 --branch homka122/all_algorithms_benchmark \
          https://github.com/SparseLinearAlgebra/LAGraph.git ~/lagraph

      - name: Build
        run: make

      - name: Check Code Formatting
        run: make format

      - name: Run Linter
        run: make lint

      - name: Test
        run: make test
